apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: auth-service
data:
  DATABASE_DRIVER: "postgres"
  MIGRATE_ON_STARTUP: "true"
  ACCESS_TOKEN_EXPIRY: "15m"
  REFRESH_TOKEN_EXPIRY: "168h"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_FROM: "noreply@yourdomain.com"
  PORT: "8080"
  ENVIRONMENT: "production"
  BASE_URL: "https://auth.yourdomain.com"
  HYDRA_ADMIN_URL: "http://hydra:4445"
  HYDRA_PUBLIC_URL: "https://oauth.yourdomain.com"
  KRATOS_ADMIN_URL: "http://kratos:4434"
  KRATOS_PUBLIC_URL: "https://identity.yourdomain.com"
  BCRYPT_COST: "12"
